// Staff Portal — unified task data source. The Project Workspace's "Tasks"
// tab (filtered by projectId), the My Tasks page (filtered by assigneeId),
// and the Task Detail Workspace (looked up by id) all read from this single
// list — never duplicate a task's data in two places. `projectId` matches a
// project's `code` in projects-data.ts. Checklist/activity/comments here are
// the INITIAL state only — the Task Detail page manages edits to them in
// local React state (there is no backend yet to persist changes to).
// Replace this whole module with a real fetch once one exists.

import type { Task } from "./types";

// Stands in for the authenticated staff member's id until Supabase auth is
// connected — happens to match MOCK_STAFF_USER's initials in mock-data.ts,
// but this is not real authentication.
export const CURRENT_USER_ID = "JD";

// Only "JD" maps to a real placeholder identity (John Doe, the demo signed-in
// user) — every other initial is a generic "Team member" since no other real
// staff records exist yet.
const ASSIGNEE_NAMES: Record<string, string> = {
  JD: "John Doe",
  AR: "Team member",
  SK: "Team member",
  MK: "Team member",
  TN: "Team member",
};

export const MOCK_TASKS: Task[] = [
  {
    id: "TASK-001",
    title: "Complete homepage UI",
    description: [
      "Complete the responsive homepage interface for the new LUNEX TECH public website.",
      "Ensure that the interface follows the established brand system and works across desktop, tablet, and mobile devices.",
    ],
    projectId: "LX-001",
    projectName: "LUNEX Website Relaunch",
    status: "in-progress",
    priority: "high",
    assigneeId: "JD",
    assigneeName: ASSIGNEE_NAMES.JD,
    dueDate: "2026-09-18",
    createdAt: "2026-09-10",
    updatedAt: "2026-09-13",
    checklist: [
      { id: "c1", label: "Design hero section", completed: true },
      { id: "c2", label: "Implement navigation", completed: true },
      { id: "c3", label: "Create homepage sections", completed: true },
      { id: "c4", label: "Optimize mobile layout", completed: false },
      { id: "c5", label: "Final testing", completed: false },
    ],
    activity: [
      { id: "a1", title: "Task created", description: "Task added to LUNEX Website Relaunch.", relativeTime: "Sep 10" },
      { id: "a2", title: "Status updated", description: "To do → In progress", relativeTime: "Sep 11" },
      { id: "a3", title: "Checklist updated", description: "Hero section completed.", relativeTime: "Sep 12" },
      { id: "a4", title: "Task updated", description: "Progress reviewed.", relativeTime: "Sep 13" },
    ],
    comments: [
      {
        id: "cm1",
        author: "John Doe",
        body: "The hero section is complete. I'm now working on responsive layouts.",
        relativeTime: "2 hours ago",
      },
      {
        id: "cm2",
        author: "Team member",
        body: "Please check the mobile navigation before moving this task to review.",
        relativeTime: "1 hour ago",
      },
    ],
  },
  {
    id: "TASK-002",
    title: "Mobile responsiveness",
    description: ["Make the homepage and key pages fully responsive across tablet and mobile breakpoints."],
    projectId: "LX-001",
    projectName: "LUNEX Website Relaunch",
    status: "todo",
    priority: "medium",
    assigneeId: "AR",
    assigneeName: ASSIGNEE_NAMES.AR,
    dueDate: "2026-09-20",
    createdAt: "2026-09-11",
    updatedAt: "2026-09-11",
    checklist: [
      { id: "c1", label: "Audit breakpoints", completed: false },
      { id: "c2", label: "Fix tablet layout", completed: false },
      { id: "c3", label: "Fix mobile layout", completed: false },
    ],
    activity: [
      { id: "a1", title: "Task created", description: "Task added to LUNEX Website Relaunch.", relativeTime: "Sep 11" },
    ],
    comments: [],
  },
  {
    id: "TASK-003",
    title: "Final UI review",
    description: ["Review the finished UI against the LUNEX design system before release."],
    projectId: "LX-001",
    projectName: "LUNEX Website Relaunch",
    status: "todo",
    priority: "medium",
    assigneeId: "SK",
    assigneeName: ASSIGNEE_NAMES.SK,
    dueDate: "2026-09-24",
    createdAt: "2026-09-11",
    updatedAt: "2026-09-11",
    checklist: [
      { id: "c1", label: "Review typography", completed: false },
      { id: "c2", label: "Review spacing", completed: false },
    ],
    activity: [
      { id: "a1", title: "Task created", description: "Task added to LUNEX Website Relaunch.", relativeTime: "Sep 11" },
    ],
    comments: [],
  },
  {
    id: "TASK-004",
    title: "Design system review",
    description: ["Confirm all components match the LUNEX design tokens."],
    projectId: "LX-001",
    projectName: "LUNEX Website Relaunch",
    status: "completed",
    priority: "low",
    assigneeId: "AR",
    assigneeName: ASSIGNEE_NAMES.AR,
    dueDate: "2026-09-10",
    createdAt: "2026-09-05",
    updatedAt: "2026-09-10",
    checklist: [
      { id: "c1", label: "Audit components", completed: true },
      { id: "c2", label: "Fix inconsistencies", completed: true },
    ],
    activity: [
      { id: "a1", title: "Task created", description: "Task added to LUNEX Website Relaunch.", relativeTime: "Sep 5" },
      { id: "a2", title: "Task completed", description: "Design system review completed.", relativeTime: "Sep 10" },
    ],
    comments: [],
  },
  {
    id: "TASK-016",
    title: "Write API documentation",
    description: ["Document the internal API endpoints used by the staff portal."],
    projectId: "LX-001",
    projectName: "LUNEX Website Relaunch",
    status: "todo",
    priority: "medium",
    assigneeId: "JD",
    assigneeName: ASSIGNEE_NAMES.JD,
    dueDate: "2026-09-28",
    createdAt: "2026-09-12",
    updatedAt: "2026-09-12",
    checklist: [
      { id: "c1", label: "Outline endpoints", completed: false },
      { id: "c2", label: "Write examples", completed: false },
    ],
    activity: [
      { id: "a1", title: "Task created", description: "Task added to LUNEX Website Relaunch.", relativeTime: "Sep 12" },
    ],
    comments: [],
  },
  {
    id: "TASK-005",
    title: "Model evaluation pipeline",
    description: [
      "Build the evaluation pipeline used to benchmark SatQuery AI's vision-language model against labeled imagery.",
    ],
    projectId: "LX-002",
    projectName: "SatQuery AI",
    status: "in-progress",
    priority: "high",
    assigneeId: "JD",
    assigneeName: ASSIGNEE_NAMES.JD,
    dueDate: "2026-09-19",
    createdAt: "2026-08-28",
    updatedAt: "2026-09-12",
    checklist: [
      { id: "c1", label: "Define benchmark set", completed: true },
      { id: "c2", label: "Automate scoring", completed: false },
      { id: "c3", label: "Report results", completed: false },
    ],
    activity: [
      { id: "a1", title: "Task created", description: "Task added to SatQuery AI.", relativeTime: "Aug 28" },
      { id: "a2", title: "Status updated", description: "To do → In progress", relativeTime: "Sep 5" },
    ],
    comments: [],
  },
  {
    id: "TASK-017",
    title: "Review SatQuery release notes",
    description: ["Review the release notes before the next SatQuery AI update goes out."],
    projectId: "LX-002",
    projectName: "SatQuery AI",
    status: "in-review",
    priority: "medium",
    assigneeId: "JD",
    assigneeName: ASSIGNEE_NAMES.JD,
    dueDate: "2026-09-16",
    createdAt: "2026-09-13",
    updatedAt: "2026-09-13",
    checklist: [
      { id: "c1", label: "Check accuracy", completed: true },
      { id: "c2", label: "Check formatting", completed: false },
    ],
    activity: [
      { id: "a1", title: "Task created", description: "Task added to SatQuery AI.", relativeTime: "Sep 13" },
      { id: "a2", title: "Status updated", description: "To do → In review", relativeTime: "Sep 13" },
    ],
    comments: [],
  },
  {
    id: "TASK-006",
    title: "Change detection accuracy testing",
    description: ["Test change-detection accuracy against the evaluation benchmark set."],
    projectId: "LX-002",
    projectName: "SatQuery AI",
    status: "todo",
    priority: "medium",
    assigneeId: "MK",
    assigneeName: ASSIGNEE_NAMES.MK,
    dueDate: "2026-09-22",
    createdAt: "2026-09-08",
    updatedAt: "2026-09-08",
    checklist: [
      { id: "c1", label: "Prepare test imagery", completed: false },
      { id: "c2", label: "Run accuracy tests", completed: false },
    ],
    activity: [{ id: "a1", title: "Task created", description: "Task added to SatQuery AI.", relativeTime: "Sep 8" }],
    comments: [],
  },
  {
    id: "TASK-007",
    title: "System evaluation",
    description: ["Run a full system evaluation ahead of the next milestone."],
    projectId: "LX-002",
    projectName: "SatQuery AI",
    status: "todo",
    priority: "high",
    assigneeId: "MK",
    assigneeName: ASSIGNEE_NAMES.MK,
    dueDate: "2026-09-26",
    createdAt: "2026-09-09",
    updatedAt: "2026-09-09",
    checklist: [
      { id: "c1", label: "Define evaluation criteria", completed: false },
      { id: "c2", label: "Run evaluation", completed: false },
    ],
    activity: [{ id: "a1", title: "Task created", description: "Task added to SatQuery AI.", relativeTime: "Sep 9" }],
    comments: [],
  },
  {
    id: "TASK-008",
    title: "API integration",
    description: ["Integrate the SatQuery AI backend with the analysis API."],
    projectId: "LX-002",
    projectName: "SatQuery AI",
    status: "completed",
    priority: "low",
    assigneeId: "JD",
    assigneeName: ASSIGNEE_NAMES.JD,
    dueDate: "2026-09-05",
    createdAt: "2026-08-20",
    updatedAt: "2026-09-04",
    checklist: [
      { id: "c1", label: "Connect endpoints", completed: true },
      { id: "c2", label: "Handle errors", completed: true },
    ],
    activity: [
      { id: "a1", title: "Task created", description: "Task added to SatQuery AI.", relativeTime: "Aug 20" },
      { id: "a2", title: "Task completed", description: "API integration completed.", relativeTime: "Sep 4" },
    ],
    comments: [],
  },
  {
    id: "TASK-009",
    title: "Marketplace UI",
    description: ["Build the marketplace shopping interface for SmartBuyX."],
    projectId: "LX-003",
    projectName: "SmartBuyX",
    status: "in-progress",
    priority: "medium",
    assigneeId: "AR",
    assigneeName: ASSIGNEE_NAMES.AR,
    dueDate: "2026-09-21",
    createdAt: "2026-08-15",
    updatedAt: "2026-09-07",
    checklist: [
      { id: "c1", label: "Design product grid", completed: true },
      { id: "c2", label: "Build cart flow", completed: false },
    ],
    activity: [
      { id: "a1", title: "Task created", description: "Task added to SmartBuyX.", relativeTime: "Aug 15" },
      { id: "a2", title: "Status updated", description: "To do → In progress", relativeTime: "Sep 1" },
    ],
    comments: [],
  },
  {
    id: "TASK-010",
    title: "Construction estimator module",
    description: ["Build the construction material estimator module."],
    projectId: "LX-003",
    projectName: "SmartBuyX",
    status: "todo",
    priority: "medium",
    assigneeId: "TN",
    assigneeName: ASSIGNEE_NAMES.TN,
    dueDate: "2026-09-25",
    createdAt: "2026-09-01",
    updatedAt: "2026-09-01",
    checklist: [
      { id: "c1", label: "Define estimation logic", completed: false },
      { id: "c2", label: "Build input form", completed: false },
    ],
    activity: [{ id: "a1", title: "Task created", description: "Task added to SmartBuyX.", relativeTime: "Sep 1" }],
    comments: [],
  },
  {
    id: "TASK-011",
    title: "Payment integration",
    description: ["Integrate a payment provider for marketplace checkout."],
    projectId: "LX-003",
    projectName: "SmartBuyX",
    status: "todo",
    priority: "high",
    assigneeId: "TN",
    assigneeName: ASSIGNEE_NAMES.TN,
    dueDate: "2026-09-30",
    createdAt: "2026-09-02",
    updatedAt: "2026-09-02",
    checklist: [
      { id: "c1", label: "Select provider", completed: false },
      { id: "c2", label: "Integrate checkout", completed: false },
    ],
    activity: [{ id: "a1", title: "Task created", description: "Task added to SmartBuyX.", relativeTime: "Sep 2" }],
    comments: [],
  },
  {
    id: "TASK-012",
    title: "Storefront build",
    description: ["Build the Deedis D2C storefront."],
    projectId: "LX-004",
    projectName: "Deedis",
    status: "completed",
    priority: "low",
    assigneeId: "SK",
    assigneeName: ASSIGNEE_NAMES.SK,
    dueDate: "2026-07-01",
    createdAt: "2026-06-01",
    updatedAt: "2026-06-28",
    checklist: [
      { id: "c1", label: "Build product pages", completed: true },
      { id: "c2", label: "Build checkout", completed: true },
    ],
    activity: [
      { id: "a1", title: "Task created", description: "Task added to Deedis.", relativeTime: "Jun 1" },
      { id: "a2", title: "Task completed", description: "Storefront build completed.", relativeTime: "Jun 28" },
    ],
    comments: [],
  },
  {
    id: "TASK-013",
    title: "Platform build",
    description: ["Build the F-Gex Groups dual-division platform."],
    projectId: "LX-005",
    projectName: "F-Gex Groups",
    status: "completed",
    priority: "low",
    assigneeId: "JD",
    assigneeName: ASSIGNEE_NAMES.JD,
    dueDate: "2026-05-01",
    createdAt: "2026-03-15",
    updatedAt: "2026-04-28",
    checklist: [
      { id: "c1", label: "Build technology division site", completed: true },
      { id: "c2", label: "Build financial division site", completed: true },
    ],
    activity: [
      { id: "a1", title: "Task created", description: "Task added to F-Gex Groups.", relativeTime: "Mar 15" },
      { id: "a2", title: "Task completed", description: "Platform build completed.", relativeTime: "Apr 28" },
    ],
    comments: [],
  },
  {
    id: "TASK-014",
    title: "Platform build",
    description: ["Build the PupilNetwork collaborative study platform."],
    projectId: "LX-006",
    projectName: "PupilNetwork",
    status: "completed",
    priority: "low",
    assigneeId: "MK",
    assigneeName: ASSIGNEE_NAMES.MK,
    dueDate: "2026-04-01",
    createdAt: "2026-02-15",
    updatedAt: "2026-03-28",
    checklist: [
      { id: "c1", label: "Build study rooms", completed: true },
      { id: "c2", label: "Build AI tutoring", completed: true },
    ],
    activity: [
      { id: "a1", title: "Task created", description: "Task added to PupilNetwork.", relativeTime: "Feb 15" },
      { id: "a2", title: "Task completed", description: "Platform build completed.", relativeTime: "Mar 28" },
    ],
    comments: [],
  },
  {
    id: "TASK-015",
    title: "Site build",
    description: ["Build the Glamroyal Events brand and booking site."],
    projectId: "LX-007",
    projectName: "Glamroyal Events",
    status: "completed",
    priority: "low",
    assigneeId: "TN",
    assigneeName: ASSIGNEE_NAMES.TN,
    dueDate: "2026-03-01",
    createdAt: "2026-01-15",
    updatedAt: "2026-02-25",
    checklist: [
      { id: "c1", label: "Build gallery", completed: true },
      { id: "c2", label: "Build booking form", completed: true },
    ],
    activity: [
      { id: "a1", title: "Task created", description: "Task added to Glamroyal Events.", relativeTime: "Jan 15" },
      { id: "a2", title: "Task completed", description: "Site build completed.", relativeTime: "Feb 25" },
    ],
    comments: [],
  },
];

export function getProjectTasks(projectId: string): Task[] {
  return MOCK_TASKS.filter((task) => task.projectId === projectId);
}

export function getMyTasks(assigneeId: string): Task[] {
  return MOCK_TASKS.filter((task) => task.assigneeId === assigneeId);
}
